spring:
  application:
    name: LMS Monolithic
  servlet:
    multipart:
      max-file-size: 10MB   # Max size for a single file
      max-request-size: 12MB
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/mylms # Replace with your DB URL & name
    username: root # Replace with your DB username
    password: root # Replace with your DB password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'update' for development, 'validate' or 'none' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Or MySQL8Dialect if appropriate

# Application specific properties (if any)
lms:
  admin:
    # For manual admin creation if needed, or to identify admin by email
    email: "admin@lms.com"
